language: python
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "2.7"
  - "3.4"
script:
  - "./.travis/run.sh"
addons:
  apt:
    packages:
     - ibus
     - python-gi
     - python3-gi
     - gir1.2-ibus-1.0
     - libwnck-3-0
     - gir1.2-wnck-3.0
