language: python
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "2.7"
  - "3.2" # Pkgs >3.2 don't allow system_site_packages
virtualenv:
  system_site_packages: true
script:
  - "./.travis/run.sh"
addons:
  apt:
    packages:
     - ibus
     - python-gi
     - python3-gi
     - libgirepository
     - gir1.2-glib-2.0
     - gir1.2-ibus-1.0
     - libwnck-3-0
     - gir1.2-wnck-3.0
     - libgtk-3-0
     - gir1.2-gtk-3.0
     - gtk+3.0
before_install:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3
